### PR TITLE
writeboost changes for v1.0.0

### PR DESCRIPTION
**Pull request by akiradeveloper**

### CODE REVIEW

**Comment by jthornber** [comment]
Why did you remove the .ruby-version?

**Comment by akiradeveloper** [comment]
.ruby-version file is only used by rbenv
which is a ruby manager that I am using.

It was my mistake to commit it.
The content of the file differs accross environments
so this shouldn't be commited.

**Comment by akiradeveloper** [comment]
Sorry, I may have said the wrong thing. I am not sure who committed the .ruby-version file but it's true  it shouldn't be in the repository.
For example, the content is 1.9.3-p545 in my machine.

**Comment by jthornber** [comment]
I do want to tie it down to a specific ruby version (patch level doesn't
matter).

**Comment by akiradeveloper** [comment]
I remove it because I need to stash/stash pop the file everytime
I commit and this is really bothering me.

How about placing version check in the ruby code like

if RUBY_VERSION != 1.9.3
  puts "ruby version must be 1.9.3"
  exit
end

The check will work because RUBY_VERSION doesn't have pXXX

irb(main):001:0> RUBY_VERSION
=> "1.9.3"
$ ruby -v
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-linux]

**Comment by jthornber** [comment]
Because RVM uses that file to automatically use the correct version.

**Comment by akiradeveloper** [comment]
Well, so the 1.9.3 for RVM implicitly means the head of 1.9.3 series.

Don't you like the idea of adding version check in ruby code and still want to keep the file? If so, I will drop the commit.

**Comment by jthornber** [comment]
I would like to keep the file please

**Comment by akiradeveloper** [comment]
OK. I dropped the commit.

**Pull request closed without merging**
